version: '3.1'
services:
  challenge-pg-db:
    image: 'postgres:latest'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: challenge
    ports:
      - '5432:5432'
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
